name: asthmaapp
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  firebase_core: ^3.1.0
  flutter_svg: ^2.0.10+1
  firebase_messaging: ^15.0.1
  http: ^1.2.1
  fluro: ^2.0.5
  flutter_local_notifications: ^17.1.2
  firebase_analytics: ^11.0.1
  realm: ^3.0.0
  url_launcher: ^6.3.0
  flutter_dash: ^1.0.0
  google_fonts: ^6.2.1
  flutter_pdfview: ^1.3.2
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/svgs/user_assets/
    - assets/svgs/child_assets/
    - assets/pdfs/
    
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/user_assets/Roboto/Roboto-Black.ttf
        - asset: assets/fonts/user_assets/Roboto/Roboto-BlackItalic.ttf
        - asset: assets/fonts/user_assets/Roboto/Roboto-Bold.ttf
        - asset: assets/fonts/user_assets/Roboto/Roboto-BoldItalic.ttf
        - asset: assets/fonts/user_assets/Roboto/Roboto-Italic.ttf
        - asset: assets/fonts/user_assets/Roboto/Roboto-Light.ttf
        - asset: assets/fonts/user_assets/Roboto/Roboto-LightItalic.ttf
        - asset: assets/fonts/user_assets/Roboto/Roboto-Medium.ttf
        - asset: assets/fonts/user_assets/Roboto/Roboto-MediumItalic.ttf
        - asset: assets/fonts/user_assets/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/user_assets/Roboto/Roboto-Thin.ttf
        - asset: assets/fonts/user_assets/Roboto/Roboto-ThinItalic.ttf
    - family: Comic Neue
      fonts:
        - asset: assets/fonts/child_assets/Comic_Neue/ComicNeue-Bold.ttf
        - asset: assets/fonts/child_assets/Comic_Neue/ComicNeue-BoldItalic.ttf
        - asset: assets/fonts/child_assets/Comic_Neue/ComicNeue-Italic.ttf
        - asset: assets/fonts/child_assets/Comic_Neue/ComicNeue-Light.ttf
        - asset: assets/fonts/child_assets/Comic_Neue/ComicNeue-LightItalic.ttf
        - asset: assets/fonts/child_assets/Comic_Neue/ComicNeue-Regular.ttf
